from __future__ import annotations

from dataclasses import dataclass, field
from typing import Mapping


RULE_PROPOSAL_DEFINED = "PROPOSAL_DEFINED"
RULE_OPERATIONALIZATION = "OUR_OPERATIONALIZATION"
RULE_UNSUPPORTED = "UNSUPPORTED"
RULE_CONFIGURED = "CONFIGURED"
RULE_DEFERRED = "DEFERRED"

APPENDIX_A_REFERENCE = "Proposal Appendix A, p.87"
APPENDIX_B_REFERENCE = "Proposal Appendix B, pp.89-93"
APPENDIX_C_REFERENCE = "Proposal Appendix C, pp.95-96"

# The resource types explicitly visible as rows in Appendix A and columns in
# Appendix B. Generation-0 may contain additional legal GenoLOM values; those
# are NOT silently assigned content rules here.
APPENDIX_A_RESOURCE_TYPES = (
    "Exercise",
    "Question",
    "Problem Statement",
    "Self-Assessment",
    "Exam",
    "Diagram",
    "Figure",
    "Graph",
    "Slide",
    "Table",
    "Narrative Text",
    "Video Clip",
    "Hypertext Document",
)


@dataclass(frozen=True, slots=True)
class OperationTemplate:
    """One operation exactly transcribed from Appendix A.

    ``uses_n`` means the proposal writes the operation with ``(n)`` where the
    current project defines n as the ordinal Source->Target distance.
    ``argument`` stores proposal literals such as ``Navigation`` or the Unpack
    hint bundle.
    """

    operation: str
    uses_n: bool = False
    argument: str | None = None
    origin: str = RULE_PROPOSAL_DEFINED
    proposal_reference: str = APPENDIX_A_REFERENCE


@dataclass(frozen=True, slots=True)
class ResourceTypeTransition:
    source: str
    target: str
    operation: str
    origin: str = RULE_PROPOSAL_DEFINED
    proposal_reference: str = APPENDIX_B_REFERENCE

    @property
    def blocks_realization(self) -> bool:
        # Appendix B labels Drop() as "not convertible" (غیر قابل تبدیل).
        return self.operation == "Drop"


@dataclass(frozen=True, slots=True)
class InteractivityTypeTransition:
    source: str
    target: str
    operation: str
    origin: str = RULE_CONFIGURED


U = OperationTemplate("Unpack", argument="hints: text, voice, video, animation")
P = OperationTemplate("Pack", uses_n=True)
E = OperationTemplate("Expand", uses_n=True)
NOP = OperationTemplate("NOP")
SD_DOWN = OperationTemplate("sdDecrease", uses_n=True)
SD_UP = OperationTemplate("sdIncrease", uses_n=True)
COG_DOWN = OperationTemplate("Cognitive_Level_down", uses_n=True)
COG_UP = OperationTemplate("Cognitive_Level_up", uses_n=True)
HTML = OperationTemplate("Export2HTML")


def ADD(action: str) -> OperationTemplate:
    return OperationTemplate("Add_Actions", argument=action)


def REMOVE(action: str) -> OperationTemplate:
    return OperationTemplate("Remove_Actions", argument=action)


# Appendix A, page 87. Keys are the proposal operation families generated by
# metadata changes; values are the exact low-level operation sequence shown in
# the table for the *source* learningResourceType.
APPENDIX_A_CONTENT_OPERATIONS: dict[
    str, dict[str, tuple[OperationTemplate, ...]]
] = {
    "Exercise": {
        "ilIncrease": (NOP,),
        "ilDecrease": (
            REMOVE("Adv_Click"),
            REMOVE("Adv_Animation"),
            REMOVE("Drag&Drop"),
            REMOVE("Adv_Drag&Drop"),
            HTML,
        ),
        "sdDecrease": (U,),
        "sdIncrease": (P,),
        "diffDecrease": (COG_DOWN, SD_DOWN),
        "diffIncrease": (COG_UP, SD_UP),
    },
    "Question": {
        "ilIncrease": (NOP,),
        # This apparently asymmetric Add_Actions(Animation) is transcribed
        # exactly from Appendix A; it is intentionally not "corrected".
        "ilDecrease": (
            REMOVE("Adv_Click"),
            ADD("Animation"),
            REMOVE("Drag&Drop"),
            REMOVE("Adv_Drag&Drop"),
            HTML,
        ),
        "sdDecrease": (U,),
        "sdIncrease": (P,),
        "diffDecrease": (COG_DOWN, SD_DOWN),
        "diffIncrease": (COG_UP, SD_UP),
    },
    "Problem Statement": {
        "ilIncrease": (NOP,),
        "ilDecrease": (
            REMOVE("Adv_Click"),
            REMOVE("Adv_Animation"),
            REMOVE("Drag&Drop"),
            REMOVE("Adv_Drag&Drop"),
            HTML,
        ),
        "sdDecrease": (U,),
        "sdIncrease": (P,),
        "diffDecrease": (COG_DOWN, SD_DOWN),
        "diffIncrease": (COG_UP, SD_UP),
    },
    "Self-Assessment": {
        "ilIncrease": (NOP,),
        "ilDecrease": (
            REMOVE("Adv_Click"),
            REMOVE("Adv_Animation"),
            REMOVE("Drag&Drop"),
            REMOVE("Adv_Drag&Drop"),
            HTML,
        ),
        "sdDecrease": (U,),
        "sdIncrease": (P,),
        "diffDecrease": (COG_DOWN, SD_DOWN),
        "diffIncrease": (COG_UP, SD_UP),
    },
    "Exam": {
        "ilIncrease": (NOP,),
        "ilDecrease": (
            REMOVE("Adv_Click"),
            REMOVE("Adv_Animation"),
            REMOVE("Drag&Drop"),
            REMOVE("Adv_Drag&Drop"),
            HTML,
        ),
        "sdDecrease": (U,),
        "sdIncrease": (P,),
        "diffDecrease": (COG_DOWN, SD_DOWN),
        "diffIncrease": (COG_UP, SD_UP),
    },
    "Diagram": {
        "ilIncrease": (
            ADD("Navigation"),
            ADD("Click"),
            ADD("Animation"),
            ADD("Hotspots"),
            ADD("TextInput"),
        ),
        "ilDecrease": (NOP,),
        "sdDecrease": (U,),
        "sdIncrease": (NOP,),
        "diffDecrease": (COG_DOWN, SD_DOWN),
        "diffIncrease": (NOP,),
    },
    "Figure": {
        "ilIncrease": (
            ADD("Navigation"),
            ADD("Click"),
            ADD("Animation"),
            ADD("Hotspots"),
            ADD("TextInput"),
        ),
        "ilDecrease": (NOP,),
        "sdDecrease": (U,),
        "sdIncrease": (NOP,),
        "diffDecrease": (COG_DOWN, SD_DOWN),
        "diffIncrease": (NOP,),
    },
    "Graph": {
        "ilIncrease": (
            ADD("Navigation"),
            ADD("Click"),
            ADD("Animation"),
            ADD("Hotspots"),
            ADD("TextInput"),
        ),
        "ilDecrease": (NOP,),
        "sdDecrease": (U,),
        "sdIncrease": (NOP,),
        "diffDecrease": (COG_DOWN, SD_DOWN),
        "diffIncrease": (NOP,),
    },
    "Slide": {
        "ilIncrease": (ADD("Navigation"), ADD("TextInput"), HTML),
        "ilDecrease": (
            REMOVE("Click"),
            REMOVE("Animation"),
            REMOVE("Hotspots"),
        ),
        "sdDecrease": (E,),
        "sdIncrease": (P,),
        "diffDecrease": (SD_DOWN,),
        "diffIncrease": (COG_UP, SD_UP),
    },
    "Table": {
        "ilIncrease": (
            ADD("Navigation"),
            ADD("Click"),
            ADD("Animation"),
            ADD("Hotspots"),
            ADD("TextInput"),
        ),
        "ilDecrease": (NOP,),
        "sdDecrease": (U,),
        "sdIncrease": (NOP,),
        "diffDecrease": (SD_DOWN,),
        "diffIncrease": (NOP,),
    },
    "Narrative Text": {
        "ilIncrease": (
            ADD("Navigation"),
            ADD("Click"),
            ADD("Animation"),
            ADD("Hotspots"),
            ADD("TextInput"),
        ),
        "ilDecrease": (NOP,),
        "sdDecrease": (E,),
        "sdIncrease": (P,),
        "diffDecrease": (SD_DOWN,),
        "diffIncrease": (SD_UP,),
    },
    "Video Clip": {
        "ilIncrease": (ADD("Navigation"), ADD("TextInput"), HTML),
        "ilDecrease": (
            REMOVE("Click"),
            REMOVE("Animation"),
            REMOVE("Hotspots"),
        ),
        "sdDecrease": (U,),
        "sdIncrease": (P,),
        "diffDecrease": (SD_DOWN,),
        "diffIncrease": (SD_UP,),
    },
    "Hypertext Document": {
        "ilIncrease": (ADD("Click"), ADD("Animation"), HTML),
        "ilDecrease": (
            REMOVE("Navigation"),
            REMOVE("Hotspots"),
            REMOVE("TextInput"),
        ),
        "sdDecrease": (E, U),
        "sdIncrease": (P,),
        "diffDecrease": (SD_DOWN,),
        "diffIncrease": (SD_UP,),
    },
}


# Appendix B, pages 89-93. Only these three source rows are proposal-defined.
# The tables also contain an anomalous "Index" Drop() row for Question and
# Problem Statement even though Index is not a visible destination header and
# is not part of the frozen Phase-1 LRT vocabulary. It is documented below but
# deliberately excluded from valid transitions.
_APPENDIX_B_ACTIONS: dict[str, dict[str, str]] = {
    "Exercise": {
        "Exercise": "==",
        "Question": "is_Same_as",
        "Problem Statement": "is_Same_as",
        "Self-Assessment": "is_Same_as",
        "Exam": "is_Same_as",
        "Diagram": "Drop",
        "Figure": "Drop",
        "Graph": "Drop",
        "Slide": "Converts_to",
        "Table": "Drop",
        "Narrative Text": "Converts_to",
        "Video Clip": "Converts_to",
        "Hypertext Document": "Converts_to",
    },
    "Question": {
        "Exercise": "is_Same_as",
        "Question": "==",
        "Problem Statement": "Drop",
        "Self-Assessment": "is_Same_as",
        "Exam": "is_Same_as",
        "Diagram": "Drop",
        "Figure": "Drop",
        "Graph": "Drop",
        "Slide": "Converts_to",
        "Table": "Drop",
        "Narrative Text": "Drop",
        "Video Clip": "Converts_to",
        "Hypertext Document": "Converts_to",
    },
    "Problem Statement": {
        "Exercise": "is_Same_as",
        "Question": "Drop",
        "Problem Statement": "==",
        "Self-Assessment": "is_Same_as",
        "Exam": "is_Same_as",
        "Diagram": "Drop",
        "Figure": "Drop",
        "Graph": "Drop",
        "Slide": "Converts_to",
        "Table": "Drop",
        "Narrative Text": "Converts_to",
        "Video Clip": "Converts_to",
        "Hypertext Document": "Converts_to",
    },
}

APPENDIX_B_DOCUMENTED_ANOMALIES = (
    {
        "source": "Question",
        "target": "Index",
        "action": "Drop",
        "note": (
            "Appendix B shows a Question Drop() Index row although Index is not "
            "a destination-column header and is not in the frozen Phase-1 LRT vocabulary."
        ),
    },
    {
        "source": "Problem Statement",
        "target": "Index",
        "action": "Drop",
        "note": (
            "Appendix B shows a Problem Statement Drop() Index row although Index "
            "is not a destination-column header and is not in the frozen Phase-1 LRT vocabulary."
        ),
    },
)


def _default_resource_type_transitions() -> dict[
    tuple[str, str], ResourceTypeTransition
]:
    return {
        (source, target): ResourceTypeTransition(
            source=source,
            target=target,
            operation=operation,
        )
        for source, targets in _APPENDIX_B_ACTIONS.items()
        for target, operation in targets.items()
    }


@dataclass(frozen=True, slots=True)
class ProposalRuleSet:
    """Authoritative proposal rules used by Milestone 4.

    Defaults are transcribed from proposal Appendices A-C. Configurable maps are
    still supported for controlled experiments, but the scientific default is
    no longer empty or guessed.
    """

    content_operations: Mapping[
        str, Mapping[str, tuple[OperationTemplate, ...]]
    ] = field(
        default_factory=lambda: {
            resource_type: dict(row)
            for resource_type, row in APPENDIX_A_CONTENT_OPERATIONS.items()
        }
    )
    resource_type_transitions: Mapping[
        tuple[str, str], ResourceTypeTransition
    ] = field(default_factory=_default_resource_type_transitions)
    interactivity_type_transitions: Mapping[
        tuple[str, str], InteractivityTypeTransition
    ] = field(default_factory=dict)
    # Implementation capability, not a proposal rule. Text-only Phase-2 V1 does
    # not pretend it has produced actual multimedia/interactive artifacts.
    unsupported_resource_types: frozenset[str] = frozenset(
        {"Simulation", "Video Clip", "Slide", "Authoring Tool"}
    )

    def content_operations_for(
        self, source_resource_type: str, action_family: str
    ) -> tuple[OperationTemplate, ...] | None:
        row = self.content_operations.get(source_resource_type)
        if row is None:
            return None
        return row.get(action_family)

    def resource_type_rule(
        self, source: str, target: str
    ) -> ResourceTypeTransition | None:
        return self.resource_type_transitions.get((source, target))

    def interactivity_type_rule(
        self, source: str, target: str
    ) -> InteractivityTypeTransition | None:
        return self.interactivity_type_transitions.get((source, target))


DEFAULT_PROPOSAL_RULES = ProposalRuleSet()


# Appendix C is a full ordinal transition matrix. The action can be generated
# without storing all cells because each matrix exactly uses direction +
# ordinal distance. The fixed project definition of n matches those cells.
_APPENDIX_C_SCALES: dict[str, tuple[str, ...]] = {
    "interactivityLevel": ("Very Low", "Low", "Medium", "High", "Very High"),
    "semanticDensity": ("Very Low", "Low", "Medium", "High", "Very High"),
    # Appendix C labels difficulty positions very-low..very-high, while the
    # GenoLOM vocabulary used by this project is Very Easy..Very Difficult.
    # We map them by ordinal position; this vocabulary reconciliation is a
    # project operationalization, while diffIncrease/diffDecrease(n) itself is
    # proposal-defined.
    "difficulty": ("Very Easy", "Easy", "Medium", "Difficult", "Very Difficult"),
}
_APPENDIX_C_PREFIXES = {
    "interactivityLevel": "il",
    "semanticDensity": "sd",
    "difficulty": "diff",
}


def appendix_c_mutation_action(field_name: str, source: str, target: str) -> str:
    """Return the exact Appendix-C action label for an ordinal transition."""

    if field_name not in _APPENDIX_C_SCALES:
        raise KeyError(f"Appendix C has no ordinal matrix for {field_name!r}.")
    scale = _APPENDIX_C_SCALES[field_name]
    if source not in scale or target not in scale:
        raise ValueError(
            f"Values {source!r}->{target!r} are outside the {field_name} scale."
        )
    delta = scale.index(target) - scale.index(source)
    if delta == 0:
        return "NOP"
    direction = "Increase" if delta > 0 else "Decrease"
    return f"{_APPENDIX_C_PREFIXES[field_name]}{direction}({abs(delta)})"


__all__ = [
    "RULE_PROPOSAL_DEFINED",
    "RULE_OPERATIONALIZATION",
    "RULE_UNSUPPORTED",
    "RULE_CONFIGURED",
    "RULE_DEFERRED",
    "APPENDIX_A_REFERENCE",
    "APPENDIX_B_REFERENCE",
    "APPENDIX_C_REFERENCE",
    "APPENDIX_A_RESOURCE_TYPES",
    "APPENDIX_A_CONTENT_OPERATIONS",
    "APPENDIX_B_DOCUMENTED_ANOMALIES",
    "OperationTemplate",
    "ResourceTypeTransition",
    "InteractivityTypeTransition",
    "ProposalRuleSet",
    "DEFAULT_PROPOSAL_RULES",
    "appendix_c_mutation_action",
]
